# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ee81b76c2b38a4ad445009d6290e23ae81429fd4f15ee4ccafe2489f4e324442922648e217d97b3de19d803fd2152ac65442add3da391de9b915f0bc21d4082

test:
  secret_key_base: 1050225ae3fe0df541d73e0a5036d3655e98f8cd7bbfe46bf31640e6dcc0afed3c68398c70d2411f5f2610afb462e4ffddc8217a49a503c6d96d3db12bae6b03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
